### ISSUE TITLE
Error while using Cursive Function Usage

### ISSUE THREAD

**Issue by hira29** [meistrari/cursive-py#11]
### Expected Behavior
The Expected behavior will be the function is called by the LLMs.

Returning res.answer

### Current Behavior
Error Message:
```
Traceback (most recent call last):
  File "/Users/engineering/git/personal_exploration/main_test.py", line 9, in <module>
    def add(a: float, b: float):
  File "/Users/engineering/git/personal_exploration/exploration310_env/lib/python3.10/site-packages/cursive/function.py", line 57, in decorator
    return CursiveFunction(function, pause=pause)
  File "/Users/engineering/git/personal_exploration/exploration310_env/lib/python3.10/site-packages/cursive/function.py", line 17, in __init__
    self.definition = function
  File "/Users/engineering/git/personal_exploration/exploration310_env/lib/python3.10/site-packages/pydantic/v1/main.py", line 405, in __setattr__
    self.__fields_set__.add(name)
AttributeError: 'CursiveFunction' object has no attribute '__fields_set__'. Did you mean: '__fields__'?
```

### Steps to Reproduce
Running this part of code:
```
import os
from cursive import cursive_function, Cursive

cursive = Cursive()

os.environ["OPENAI_API_KEY"] = "<OPENAI-API-KEY>"

@cursive_function()
def add(a: float, b: float):
    """
    Adds two numbers.

    a: The first number.
    b: The second number.
    """
    return a + b

res = cursive.ask(
    prompt='What is the sum of 232 and 243?',
    functions=[add],
)

print({
        'model': res.model,
        'message': res.answer,
        'usage': res.usage.total_tokens,
        'convo': res.conversation.messages,
    })
```

### Context (Environment)
Python 3.10.10 
MacOS 14 Sonoma
Macbook Pro M2
cursivepy 0.7.0

### Detailed Description
I follow the instruction for function usage available here : https://github.com/meistrari/cursive-py#functions
Got an error instead.

**Comment by henrycunh** [comment]
oh oh! this is a incompatibility with a Pydantic V1, I think it was introduced on #8 

On it, sorry for the hassle!
